CREATE TABLE WIKI_PAGE
    (
        PAGE_NAME           VARCHAR (100)   CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
	PAGE_VERSION        INTEGER																						NOT NULL,
	PAGE_MODIFIED       DATETIME,
	PAGE_MODIFIED_BY    VARCHAR (50)    CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
	PAGE_TEXT           MEDIUMTEXT      CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
	PRIMARY KEY  (PAGE_NAME, PAGE_VERSION),
	UNIQUE KEY PAGE_NAME (PAGE_NAME, PAGE_VERSION),
	KEY PAGE_MODIFIED_IX (PAGE_MODIFIED)
    );

CREATE TABLE WIKI_ATT
    (
        ATT_PAGENAME	VARCHAR	(100)   CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
        ATT_FILENAME	VARCHAR	(100)   CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
        ATT_VERSION	INTEGER 																					NOT NULL,
        ATT_MODIFIED	DATETIME,
        ATT_MODIFIED_BY VARCHAR	(50)    CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
        ATT_DATA	MEDIUMBLOB,
        ATT_LENGTH 	INTEGER,
        PRIMARY KEY  (ATT_PAGENAME,ATT_FILENAME,ATT_VERSION),
        UNIQUE KEY ATT_PAGENAME (ATT_PAGENAME,ATT_FILENAME,ATT_VERSION),
        KEY ATT_MODIFIED_IX (ATT_MODIFIED)
    );