CREATE TABLE WIKI_PAGE
    (
        PAGE_NAME          VARCHAR (100)  NOT NULL,
        PAGE_VERSION       INTEGER        NOT NULL,
        PAGE_MODIFIED      DATETIME,
        PAGE_MODIFIED_BY   VARCHAR (50),
        PAGE_TEXT          MEDIUMTEXT,
        PRIMARY KEY (PAGE_NAME),
        UNIQUE (PAGE_NAME),
        INDEX PAGE_MODIFIED_IX (PAGE_MODIFIED)
    );
CREATE TABLE WIKI_PAGE_VERSIONS
    (
        VERSION_NAME          VARCHAR (100)  NOT NULL,
        VERSION_NUM           INTEGER        NOT NULL,
        VERSION_MODIFIED      DATETIME,
        VERSION_MODIFIED_BY   VARCHAR (50),
        VERSION_TEXT          MEDIUMTEXT,
        PRIMARY KEY (VERSION_NAME, VERSION_NUM),
        UNIQUE (VERSION_NAME, VERSION_NUM)
    );

CREATE TABLE WIKI_ATT
    (
        ATT_PAGENAME      VARCHAR (100)  NOT NULL,
        ATT_FILENAME      VARCHAR (100)  NOT NULL,
        ATT_VERSION       INTEGER        NOT NULL,
        ATT_MODIFIED      DATETIME,
        ATT_MODIFIED_BY   VARCHAR (50),
        ATT_DATA          MEDIUMBLOB,
        ATT_LENGTH        INTEGER,
        PRIMARY KEY (ATT_PAGENAME, ATT_FILENAME, ATT_VERSION),
        UNIQUE (ATT_PAGENAME, ATT_FILENAME, ATT_VERSION),
        INDEX ATT_MODIFIED_IX (ATT_MODIFIED)
    );
